
spring:
  datasource:
    url: jdbc:postgresql://192.168.78.136:5432/postgres
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

server:
  port: 8080

kelso:
  app:
    jwtCookieName: kelso
    jwtSecret: 12345678910
    jwtExpirationMs: 86400000