
spring:
  datasource:
    url: jdbc:postgresql://192.168.78.136:5432/kelso
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

server:
  port: 8080

kelso:
  app:
    jwtCookieName: kelso
    jwtSecret: 80844d0228eed81acf109fc54bb253bf9c849d6b91e92e0f1fade2c07c138dd6
    jwtExpirationMs: 86400000